language: node_js
dist: bionic
cache:
  directories:
    - "node_modules"
node_js:
  - lts/*
notifications:
  email: false
branches:
  only:
  - master
script:
  - npm run update-caniuse
  - npm test
  - npm run build:travis
  - npm run build:sw
deploy:
  provider: pages
  local-dir: dist
  skip-cleanup: true
  github-token: $GH_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
