name: Node Test

on: [push]

jobs:
  run_psi:
    runs-on: ubuntu-latest
    name: Running NPM Test
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install
        run: |
          npm ci
      - name: Build
        run: |
          npm run build
      - name: Test
        run: |
          npm t
