name: PageSpeed Insights

on: [push]

jobs:
  run_psi:
    runs-on: ubuntu-latest
    name: Running PageSpeed Insights
    steps:
    - name: Waiting for 200 from the Netlify Preview
      uses: jakepartusch/wait-for-netlify-action@v1
      id: waitFor200
      with:
      site_name: "modernize-ng1"
     - name: Running Page Speed Insights
       uses: jakepartusch/psi-action@v1
       id: psi
       with:
         url: ${{ steps.waitFor200.outputs.url }}
         threshold: 50
         strategy: mobile
