on: [push]

jobs:
  run_psi:
    runs-on: ubuntu-latest
    name: Running PageSpeed Insights
    steps:
     - name: Checkout
       uses: actions/checkout@v1
     - name: Running Page Speed Insights
       uses: jakepartusch/psi-action@v1
       id: psi
       with:
         url: "https://modernize-ng1.edm00se.codes"
         threshold: 85
         strategy: mobile
